services:
  pgsql-investment-wallet:
    image: postgres:17.6
    container_name: pgsql-investment-wallet
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pgsql-wallet-password
      POSTGRES_USER: pgsql-master
    networks:
      - wallet-net
    volumes:
      - ./01-create-database-wallet.sql:/docker-entrypoint-initdb.d/01-create-database-wallet.sql

      - ./pg_data:/var/lib/postgresql/data
networks:
  wallet-net:
    driver: bridge