services:
  pgsql-investment-wallet:
    image: postgres:17.6
    container_name: pgsql-investment-wallet
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pgsql-wallet-password
      POSTGRES_USER: pg-wallet-admin
      POSTGRES_DB: investment-wallet
    networks:
      - wallet-net
    volumes:
      - ./pg_data:/var/lib/postgresql/data
networks:
  wallet-net:
    driver: bridge